### PR TITLE
fix: prevent duplicate vault entries when renaming accounts

### LINKED ISSUE #112: bug: renaming account creates duplicate vault entry
## Description

When renaming an account, the vault ends up with two entries containing the same seed/identity but different names. After locking and unlocking, both entries appear in the account list.

## Steps to reproduce

1. Create a new wallet with the default name "main"
2. Go to Manage Accounts and rename "main" to any other name (e.g. "123")
3. Lock the wallet
4. Unlock the wallet
5. Open Manage Accounts — two identical addresses are shown

## Root cause

The rename handler in `src/pages/manage-accounts.tsx:276-278` uses `vault.addSeed({ name, seed, overwrite: true })`. The SDK's `addSeed` matches entries by **name**, not by identity. Since the name is changing (e.g., "main" → "123"), no existing entry is found to overwrite — a new entry is created while the old one remains.

On unlock, `vault.list()` returns both entries, and `saveCachedAccounts` stores both to the cache.

**SDK reference:** `node_modules/@qubic-labs/sdk/dist/src/vault-browser.js` — `entries` is a `Map` keyed by name, and `overwrite` only checks `entries.has(name)`.

## Affected version

All beta releases

### PR DESCRIPTION
**Pull request by alez04**
## Summary
- rename vault accounts by identity instead of relying on name-based overwrite behavior
- automatically repair duplicate vault entries that share the same identity during trusted vault-open flows
- refresh cached accounts from the normalized vault list after rename, unlock, and manual load

## Verification
- npm run lint
- npm run build

Fixes #112

### CODE REVIEW

File: src/pages/manage-accounts.tsx [hunk 1]
```diff
@@ -268,24 +271,36 @@ const ManageAccounts = () => {
...
         if (account.identity === currentIdentity) {
           setOnboarded(account.identity, name.trim())
         }
       }
-      const updated = orderedAccounts.map((entry) =>
-        entry.identity === account.identity ? { ...entry, name: name.trim() } : entry,
-      )
-      saveCachedAccounts(updated.filter((entry) => !entry.watchOnly))
-      setAccounts(updated)
+      if (account.watchOnly) {
```
Comment (sallymoc) [inline src/pages/manage-accounts.tsx]: @alez04  The if (account.watchOnly) { saveCachedAccounts(...) } block after the if/else should be removed. Vault entries and watch-only accounts are stored separately (accountCache vs watchOnlyAccounts in localStorage). A watch-only rename doesn't change vault entries, so calling saveCachedAccounts here writes unchanged data and triggers a spurious wallet-account-updated event.
