### PR TITLE
fix: update data syncing

### LINKED ISSUE #87: fix: to update the data syncing
- /v1/latest-stats endpoint usage:

Fetched every 5 minutes on a dedicated timer, independent from the main data refresh cycle (balances, transactions, tick).
The response is used exclusively to derive the USD valuation of wallet balances (price field multiplied by account amounts).

- switch to /v1/tick-info for current tick data and refresh every 60s and use it for:

-- Transfer form UI hint (showing approximate current tick in advanced options)
Note: At actual send time — make a new call for a fresh value and use that value in the trx object before to sign
-- Future: dApp transaction tick validation

- Active account balance + assets => fetch every 30 seconds for the selected account and also an initial refresh when the user selects it or on demand when user taps refresh

- Transactions (home + history)  => fetch every 30 seconds for the selected account and also an initial refresh when the user selects it or on demand when user tap refresh. Aligned with the account balance refresh.

- Refresh balance every 5 min for non-active accounts (shown in the header popover), with an immediate refresh when the user switches to that account (can be aligned with the latest-stats)

### PR DESCRIPTION
**Pull request by ahmed-tarek-salem**
Closes https://github.com/qubic/wallet-extension/issues/87

### CODE REVIEW

File: src/lib/network-stats.ts [hunk 1]
```diff
@@ -24,6 +41,14 @@ export const fetchLatestStats = async (): Promise<LatestStatsResponse> => {
   return response.json() as Promise<LatestStatsResponse>
 }
 
+export const fetchTickInfo = async (): Promise<TickInfoResponse> => {
+  const response = await fetch('https://rpc.qubic.org/v1/tick-info')
```
Comment (sallymoc) [inline src/lib/network-stats.ts]: @ahmed-tarek-salem  RPC base URL https://rpc.qubic.org hardcoded. Same URL exists in app.tsx and assets.ts. It should be a shared constant.
Also, tick-info is in live API, prefix /live/ is missing.

File: src/components/app-header.tsx
Comment (sallymoc) [inline src/components/app-header.tsx:116]: @ahmed-tarek-salem it's not something specific to this PR, but handleCopyIdentity duplicates the clipboard + toast logic already provided by the useClipboardCopy hook. Consider using the hook instead to keep clipboard behavior consistent across the app.
