### PR TITLE
fix(pending): handle never-confirmed transactions as failed with resend/delete flow

### LINKED ISSUE #69: Handle pending transactions that were never added to the tickchain
When a transaction is submitted but never confirmed by the network (e.g. it was never added to the tickchain), the pending state currently has no way to detect this. The transaction stays as "pending" indefinitely.

There are two API options to detect the latest tick processed by the archiver:

- `validForTick` field from the `getTransactionsForIdentity` response (already available)
- [`getLastProcessedTick`](https://docs.qubic.org/apis/query#tag/archive/GET/getLastProcessedTick) endpoint

Evaluate which one is more appropriate. Either way, the logic is:

- If the archiver's last processed tick > pending transaction's `targetTick` **and** the API never returned the transaction hash → the transaction was never added to the tickchain and should be marked as **failed**.
- If the API returns the transaction → it was confirmed, resolve normally.
- If the archiver's last processed tick < pending transaction's `targetTick` → still pending, keep waiting.

### What needs to change

1. Add a `status` field to `PendingTransaction` in `src/lib/pending-transactions.ts` (e.g. `'pending' | 'failed'`).
2. In `resolvePendingTransactions`, compare the archiver's last processed tick against each pending transaction's `targetTick`. If the archiver has processed past the target tick without returning the hash, mark the transaction as `failed` instead of deleting it.
3. Show failed transactions at the top of the history and home page with distinct styling (different from the amber pending state) to indicate the transaction was not processed.
4. Both pending and failed transactions should be displayed at the top of the list, separate from the ones returned by the query service. This avoids breaking pagination.
5. Failed transactions should offer the possibility to **resend** — opening the transfer form with the original transaction data prefilled (recipient, amount, etc.).

### Reference

In the mobile and web wallet, transactions that were never added to the chain are already displayed at the top together with pending ones (not mixed with the paginated results), and they support resending with prefilled data.

### PR DESCRIPTION
**Pull request by alez04**
this pr fixes pending transactions that were never added to the tickchain and stayed pending forever.

- added status to pending tx model: pending | failed

- updated pending resolver logic:
  - confirmed hash from api -> remove pending tx
  - archiver processed tick > target tick and hash not found -> mark as failed
  - otherwise keep as pending

- used archiver progress for resolution:
  - validForTick from transaction pages
  - useLastProcessedTick on tx details flow

- history/home now render local pending + failed entries at the top, separate from paginated api results
- added distinct failed styling (separate from amber pending)
- added resend flow for failed tx (opens transfer with prefilled recipient + amount)
- fixed transfer prefill persistence from query params (no lost values on navigation/remount)
- after successful resend, original failed local entry is removed
- added manual delete action for failed entries on home/history
- added i18n keys:
  - history.failed
  - history.resend
  - history.deleteFailed

### CODE REVIEW

File: src/components/pages/home/transactions-preview.tsx [hunk 1]
```diff
@@ -1,54 +1,186 @@
...
+    const counterpartyLabel = isSimpleTransfer
+      ? isIncoming
+        ? t('history.from', { address: truncateString(counterparty) })
+        : t('history.to', { address: truncateString(counterparty) })
+      : truncateString(counterparty)
+    const Icon = isIncoming ? ReceiveIcon : SendIcon
+    const isPending = isTransactionPending(tx.hash)
+    const isFailed = isTransactionFailed(tx.hash)
+    const canResend = isFailed && Number(tx.inputType) === 0 && Boolean(tx.destination)
+
```
Comment (sallymoc) [inline src/components/pages/home/transactions-preview.tsx:96]: @alez04  canResend can be extracted to a util because (without the isFailed) is also in transactions-preview.
Also, it's not only for inputType = 0. We also support transfer assets so can be repeated as well.

File: src/pages/history.tsx [hunk 2]
```diff
@@ -197,9 +226,169 @@ const History = () => {
...
+            )}
+
+          {(pendingTopItems.length > 0 || failedTopItems.length > 0) && (
+            <motion.div className="space-y-2" variants={itemMotion}>
+              {pendingTopItems.length > 0 && (
+                <div className="space-y-2">
+                  <span className="text-[11px] font-semibold uppercase text-muted-foreground/70">
+                    {t('history.pending')}
+                  </span>
+                  {pendingTopItems.map((tx) => {
```
Comment (sallymoc) [inline src/pages/history.tsx]: @alez04  The row rendering for pending and normal transactions share the same structure — icon circle, label, counterparty, amount, and hash/tick/type footer — with only styling and action differences.

transactions-preview.tsx already solves this well with a single renderRow function that handles all three states. The same approach could work here — extract a <HistoryRow> component (or a renderRow function like the preview does) that receives the transaction + status and conditionally applies the styling/actions.

File: src/pages/home.tsx [hunk 3]
```diff
@@ -93,6 +93,15 @@ const Home = () => {
     () => transactions.data?.pages.flatMap((page) => page.transactions) ?? [],
     [transactions.data],
   )
+  const archiverProcessedTick = useMemo(() => {
```
Comment (sallymoc) [inline src/pages/home.tsx:97]: @alez04  This archiverProcessedTick computation is duplicated identically in history.tsx. Consider extracting it to a shared helper (e.g. getArchiverProcessedTick(pages)) to avoid maintaining the same logic in two places.

File: src/pages/history.tsx [hunk 4]
```diff
@@ -139,10 +147,121 @@ const History = () => {
...
+            className={`text-sm font-semibold ${
+              isPending
+                ? 'text-amber-700 dark:text-amber-300'
+                : isIncoming
+                  ? 'text-primary'
+                  : 'text-[var(--destructive)]'
+            }`}
+          >
+            {isIncoming ? '+' : '-'}
+            {formatQus(tx.amount)}
```
Comment (sallymoc) [inline src/pages/history.tsx]: formatQus back here?

File: src/pages/history.tsx [hunk 5]
```diff
@@ -197,9 +316,116 @@ const History = () => {
...
+                              <span className="text-xs text-muted-foreground">
+                                {counterpartyLabel}
+                              </span>
+                            </div>
+                          </div>
+                          <div className="flex items-center gap-2">
+                            <span className="text-sm font-semibold text-red-700 dark:text-red-300">
+                              {isIncoming ? '+' : '-'}
+                              {formatQus(tx.amount)}
+                            </span>
```
Comment (sallymoc) [inline src/pages/history.tsx:440]: formatQus back here?

File: src/pages/history.tsx [hunk 6]
```diff
@@ -9,14 +9,15 @@ import { useEffect, useMemo, useState } from 'react'
...
   getPendingTransactionsForIdentity,
   PENDING_SETTLED_EVENT,
-  isTransactionPending,
+  removePendingTransaction,
   resolvePendingTransactions,
   usePendingTransactionsVersion,
 } from '@/lib/pending-transactions'
 import { getCurrentIdentity } from '@/lib/accounts'
-import { useLatestStats } from '@/lib/network-stats'
 import HistoryEmptyState from '@/components/pages/history/history-empty-state'
```
Comment (sallymoc) [inline src/pages/history.tsx:22]: formatQus back here?

**Comment by sallymoc** [comment]
@alez04 
after successful resend, original failed local entry is removed
-> please only remove it when user do it

**Comment by sallymoc** [comment]
@alez04 please rebase from dev

**Review by sallymoc — APPROVED** [review]
